// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://fyeixgdybduqknlolpxb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5ZWl4Z2R5YmR1cWtubG9scHhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjM4NjksImV4cCI6MjA3MjMzOTg2OX0.M1VYif9B6jeMFX1oWOWM3235mh8B5o-1MzlW7Ccjx24";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);